### Импорт библиотек

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

### Создание данных для классификации

In [3]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=10000, n_features=4, random_state=42)

### Разбиение на тренировочную и тестовую выборки

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

### Обучение случайного леса как пример

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix

**Обучение модели**

In [6]:
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

**Матрица ошибок 2x2 (Confusion Matrix 2x2)**

Матрица ошибок 2x2 является основным инструментом для анализа бинарной классификации, когда у нас есть два класса: положительный и отрицательный. Она представляет собой таблицу 2x2, где строки представляют фактические классы, а столбцы - предсказанные классы.

|                | Предсказанный положительный | Предсказанный отрицательный |
|----------------|---------------------------|---------------------------|
| Фактический положительный | True Positive (TP)        | False Negative (FN)       |
| Фактический отрицательный | False Positive (FP)       | True Negative (TN)        |

**Определения:**
- True Positive (TP): Количество случаев, когда модель правильно предсказала положительный класс.
- True Negative (TN): Количество случаев, когда модель правильно предсказала отрицательный класс.
- False Positive (FP): Количество случаев, когда модель ошибочно предсказала положительный класс (ошибочно "ложное срабатывание").
- False Negative (FN): Количество случаев, когда модель ошибочно предсказала отрицательный класс (ошибочно "пропустила").

In [7]:
confusion_matrix(y_test, rfc.predict(X_test))

array([[1169,   73],
       [  75, 1183]], dtype=int64)

### Реализация перцептрона

Искусственный перцептрон:

<image src="https://th.bing.com/th/id/OIP.JmcVLnBXKpxSEOVM2P1IzAHaFP?pid=ImgDet&rs=1" alt="Искусственный перцептрон">

In [8]:
from sklearn.base import BaseEstimator

class Perceptron(BaseEstimator):

    def __init__(self, activalion_function = 'step') -> None:
        self.weights = []
        self.activalion_function = activalion_function

    def fit(self, X_train, y_train):

        n, l = X_train.shape
        self.weights = np.zeros(l+1)    # Определяю первоначальные нулевые веса

        # Добавляем bias в тренировочную выборку
        X_train = np.hstack([np.ones(n).reshape(-1, 1), X_train])

        for i in range(1):
            a = self.get_transfer_function(X_train[i])
            if self.get_activation_function(a) > y_train[i]:
                self.weights -= X_train[i]
            elif self.get_activation_function(a) < y_train[i]:
                self.weights += X_train[i]
    
    def predict(self, X_test):

        X_test = np.hstack([np.ones(X_test.shape[0]).reshape(-1, 1), X_test])
        y_prob = X_test @ self.weights
        
        if self.activalion_function == 'sigmoid':
            return np.where(1/(1 + np.exp(-y_prob)) > 0.5, 1, 0)
        else:
            return np.where(y_prob > 0, 1, 0)

    def get_transfer_function(self, X):
        return X @ self.weights
    
    def get_activation_function(self, a):
        if self.activalion_function == 'step':
            if a > 0:
                return 1
            else:
                return 0
        elif self.activalion_function == 'ReLU':
            f = np.max([0, a])
            if f > 0:
                return 1
            else:
                return 0
        elif self.activalion_function == 'sigmoid':
            f = 1/(1 + np.exp(-a))
            if f > 0.5:
                return 1
            else:
                return 0

In [9]:
perceptron = Perceptron(activalion_function='sigmoid')
perceptron.fit(X_train, y_train)
perceptron.predict(X_test)

array([0, 1, 0, ..., 0, 1, 0])

In [10]:
confusion_matrix(y_test, perceptron.predict(X_test))

array([[ 960,  282],
       [  57, 1201]], dtype=int64)

In [23]:
X = np.array([[1, 2, 3, 4], [2, 3, 4, 5]]).reshape(-1, 2)
w = np.array([6, 7]).reshape(-1, 1)

In [24]:
X.shape

(4, 2)

In [25]:
w.shape

(2, 1)